# Generated by Django 5.2.3 on 2026-08-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0004_alter_agent_id_proof_alter_agent_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCurrentLocation',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_location', serialize=False, to='agent.agent')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('place_name', models.CharField(blank=True, default='', max_length=255)),
                ('building', models.CharField(blank=True, default='', max_length=255)),
                ('road', models.CharField(blank=True, default='', max_length=255)),
                ('neighbourhood', models.CharField(blank=True, default='', max_length=255)),
                ('suburb', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('postcode', models.CharField(blank=True, default='', max_length=32)),
                ('address_text', models.TextField(blank=True, default='')),
                ('geocode_provider', models.CharField(blank=True, default='', max_length=32)),
                ('session_active', models.BooleanField(db_index=True, default=False)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent current location',
                'verbose_name_plural': 'Agent current locations',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
