"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load_dotenv(BASE_DIR / '.env')
if os.path.exists(BASE_DIR / ".env"):
    load_dotenv(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS", ""
).split(",")

# Clean empty values (important)
CSRF_TRUSTED_ORIGINS = [o for o in CSRF_TRUSTED_ORIGINS if o]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'whitenoise.runserver_nostatic',  # For serving static files in development
    'rest_framework',  # Added for DRF
    
    # Local apps
    'main',  # Add this line to include the main app for management commands
    'headquater.apps.HeadquaterConfig',
    'branch.apps.BranchConfig',
    'agent.apps.AgentConfig',
    'loan.apps.LoanConfig',
    'savings.apps.SavingsConfig',
    'data_import.apps.DataImportConfig',
]

AUTH_USER_MODEL = 'headquater.HeadquarterEmployee'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'headquater.middleware.TrialUserExpiryMiddleware',  # Trial user expiry check
]

# Simplified static file serving for production with WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'main.urls'

# Templates configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Add project-level templates directory
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql' if os.environ.get('DATABASE') == 'postgresql' else 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DBNAME', BASE_DIR / 'db.sqlite3'),
    }
}

# Add PostgreSQL specific settings if using PostgreSQL
if os.environ.get('DATABASE') == 'postgresql':
    DATABASES['default'].update({
        'USER': os.environ.get('DBUSER'),
        'PASSWORD': os.environ.get('DBPASS'),
        'HOST': os.environ.get('DBHOST'),
        'PORT': os.environ.get('DBPORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    })
    # # Update DATABASE_URL for any third-party apps that might use it
    # os.environ['DATABASE_URL'] = f"postgresql://{os.environ.get('DBUSER')}:{os.environ.get('DBPASS')}@{os.environ.get('DBHOST')}:{os.environ.get('DBPORT', '5432')}/{os.environ.get('DBNAME')}"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


import os
from dotenv import load_dotenv
load_dotenv()

# Email Backend Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', '')
HQ_NOTIFICATION_EMAIL = os.environ.get('HQ_NOTIFICATION_EMAIL', '')


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL to use when referring to static files (in templates, etc.)
STATIC_URL = '/static/'

# Directories where Django will look for additional static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'static/dist',  # Add Vite output directory
]

# Directory where collected static files will be stored (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploaded files)
MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/hq/login/'
LOGIN_REDIRECT_URL = '/hq/dashboard/'
LOGOUT_REDIRECT_URL = '/hq/login/'
PASSWORD_CHANGE_URL = '/hq/password_change/'
PASSWORD_CHANGE_REDIRECT_URL = '/hq/login/'

# Session timeout settings for automatic logout on inactivity
# Session expires after 30 minutes of inactivity
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep session active until timeout
SESSION_SAVE_EVERY_REQUEST = True  # Update session expiry on every request

# Production security settings for sessions
SESSION_COOKIE_SECURE = True  # Only send cookies over HTTPS in production
SESSION_COOKIE_HTTPONLY = True  # Prevent XSS attacks via JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection - allows safe cross-site requests
