# Generated by Django 5.2.3 on 2026-01-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_initial'),
        ('headquater', '0002_alter_headquarteremployee_image_and_more'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccountApplication',
            fields=[
                ('application_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('product_type', models.CharField(choices=[('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit')], max_length=10)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tenure_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_applications', to='agent.agent')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_applications', to='headquater.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_applications', to='loan.customerdetail')),
            ],
        ),
    ]
