# Generated by Django 5.2.3 on 2026-01-21 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('type_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_saving_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saving Type',
                'verbose_name_plural': 'Saving Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavingInterest',
            fields=[
                ('interest_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('rate_of_interest', models.DecimalField(decimal_places=2, help_text='Interest rate in percentage (e.g., 12.50 for 12.5%)', max_digits=5)),
                ('description', models.CharField(blank=True, help_text='Optional description for this interest rate', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_saving_interests', to=settings.AUTH_USER_MODEL)),
                ('saving_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_rates', to='savings.savingtype')),
            ],
            options={
                'verbose_name': 'Saving Interest Rate',
                'verbose_name_plural': 'Saving Interest Rates',
                'ordering': ['rate_of_interest'],
                'unique_together': {('saving_type', 'rate_of_interest')},
            },
        ),
        migrations.CreateModel(
            name='SavingTenure',
            fields=[
                ('tenure_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('value', models.PositiveIntegerField(help_text='Duration value (e.g., 365 for 365 days)')),
                ('unit', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text="Unit of duration (e.g., 'days', 'months', 'years')", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_saving_tenures', to=settings.AUTH_USER_MODEL)),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenures', to='savings.savinginterest')),
            ],
            options={
                'verbose_name': 'Saving Tenure',
                'verbose_name_plural': 'Saving Tenures',
                'ordering': ['value', 'unit'],
                'unique_together': {('interest_rate', 'value', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='SavingInvestAmount',
            fields=[
                ('invest_amount_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_saving_invest_amounts', to=settings.AUTH_USER_MODEL)),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_amounts', to='savings.savingtype')),
            ],
            options={
                'verbose_name': 'Saving Invest Amount',
                'verbose_name_plural': 'Saving Invest Amounts',
                'ordering': ['amount'],
                'unique_together': {('saving_type', 'amount')},
            },
        ),
    ]
