# Generated by Django 5.2.3 on 2026-01-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsaccountapplication_interest_rate_savingtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsaccountapplication',
            name='principal_amount',
        ),
    ]
