# Generated by Django 5.2.3 on 2026-01-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_remove_savingsaccountapplication_principal_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingInvestAmount',
        ),
    ]
