# Generated by Django 5.2.3 on 2026-01-23 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_delete_savinginvestamount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savingtenure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savingtenure',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='savingtenure',
            name='created_by',
        ),
        migrations.CreateModel(
            name='DailyProduct',
            fields=[
                ('daily_product_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Product',
                'verbose_name_plural': 'Daily Products',
                'ordering': ['deposit_amount', 'interest_rate', 'tenure'],
                'unique_together': {('deposit_amount', 'interest_rate', 'tenure')},
            },
        ),
        migrations.CreateModel(
            name='OneTimeDeposit',
            fields=[
                ('one_time_deposit_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_one_time_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One Time Deposit',
                'verbose_name_plural': 'One Time Deposits',
                'ordering': ['deposit_amount', 'interest_rate', 'tenure'],
                'unique_together': {('deposit_amount', 'interest_rate', 'tenure')},
            },
        ),
        migrations.DeleteModel(
            name='SavingInterest',
        ),
        migrations.DeleteModel(
            name='SavingTenure',
        ),
    ]
