# Generated by Django 5.2.3 on 2026-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_remove_savingtenure_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyproduct',
            options={'ordering': ['deposit_amount', 'interest_rate', 'tenure', 'tenure_unit'], 'verbose_name': 'Daily Product', 'verbose_name_plural': 'Daily Products'},
        ),
        migrations.AlterModelOptions(
            name='onetimedeposit',
            options={'ordering': ['deposit_amount', 'interest_rate', 'tenure', 'tenure_unit'], 'verbose_name': 'One Time Deposit', 'verbose_name_plural': 'One Time Deposits'},
        ),
        migrations.AlterUniqueTogether(
            name='dailyproduct',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='onetimedeposit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyproduct',
            name='tenure_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='days', max_length=20),
        ),
        migrations.AddField(
            model_name='onetimedeposit',
            name='tenure_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='months', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailyproduct',
            unique_together={('deposit_amount', 'interest_rate', 'tenure', 'tenure_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='onetimedeposit',
            unique_together={('deposit_amount', 'interest_rate', 'tenure', 'tenure_unit')},
        ),
    ]
