# Generated by Django 5.2.3 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_alter_dailyproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='tenure_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
