# Generated by Django 5.2.3 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_savingsaccountapplication_tenure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='savingsaccountapplication',
            name='tenure_unit',
        ),
    ]
