# Generated by Django 5.2.3 on 2026-01-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_savingsaccountapplication_product_id_remove_tenure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='maturity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='surrender_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='surrender_status',
            field=models.CharField(blank=True, choices=[('none', 'No Surrender'), ('requested', 'Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='none', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='withdraw_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='withdraw_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingsaccountapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('success', 'Success'), ('reject', 'Rejected'), ('rejected_by_branch', 'Rejected by Branch'), ('inactive', 'Inactive'), ('document_requested', 'Document Requested by Branch'), ('resubmitted', 'Resubmitted - Pending Branch Review'), ('branch_document_accepted', 'Branch Accepted Document'), ('branch_approved', 'Branch Approved - Pending HQ Approval'), ('branch_resubmitted', 'Reuploaded - Pending HQ review'), ('hq_document_accepted', 'HQ Accepted Document'), ('hq_resubmitted', 'HQ Requested Resubmission'), ('hq_approved', 'HQ Approved'), ('hq_rejected', 'HQ Rejected'), ('disbursed', 'Disbursed'), ('disbursed_fund_released', 'Disbursed - Fund Released'), ('document_requested_by_hq', 'Document Requested by HQ')], default='pending', max_length=32),
        ),
    ]
