# Generated by Django 5.2.3 on 2026-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_savingsaccountapplication_maturity_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
