# Generated by Django 5.2.3 on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_savingsaccountapplication_rejection_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsaccountapplication',
            old_name='tenure_months',
            new_name='tenure',
        ),
    ]
