# Generated by Django 5.2.3 on 2026-02-02 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
        ('branch', '0002_initial'),
        ('headquater', '0002_alter_headquarteremployee_image_and_more'),
        ('savings', '0011_rename_tenure_months_to_tenure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='account_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='hq_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsaccountapplication',
            name='hq_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_approved_savings_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsaccountapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('success', 'Success'), ('reject', 'Rejected'), ('rejected_by_branch', 'Rejected by Branch'), ('inactive', 'Inactive'), ('document_requested', 'Document Requested by Branch'), ('resubmitted', 'Reuploaded - Pending branch approve'), ('branch_document_accepted', 'Branch Accepted Document'), ('branch_approved', 'Branch Approved - Pending HQ Approval'), ('branch_resubmitted', 'Reuploaded - Pending HQ review'), ('hq_document_accepted', 'HQ Accepted Document'), ('hq_resubmitted', 'HQ Requested Resubmission'), ('hq_approved', 'HQ Approved'), ('hq_rejected', 'HQ Rejected'), ('disbursed', 'Disbursed'), ('disbursed_fund_released', 'Disbursed - Fund Released'), ('document_requested_by_hq', 'Document Requested by HQ')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='SavingsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('collection_type', models.CharField(choices=[('rd_installment', 'RD Installment'), ('fd_deposit', 'FD Deposit'), ('interest', 'Interest'), ('penalty', 'Penalty'), ('withdrawal', 'Withdrawal'), ('maturity_payout', 'Maturity Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.DateField()),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='savings.savingsaccountapplication')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_transactions', to='agent.agent')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_transactions', to='headquater.branch')),
                ('collected_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_collections', to='agent.agent')),
                ('collected_by_branch_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_transactions', to='branch.branchemployee')),
            ],
        ),
    ]
