# Generated by Django 5.2.3 on 2026-02-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0012_savingsaccountapplication_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingscollection',
            name='installment_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingscollection',
            name='is_collected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savingscollection',
            name='is_expected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='savingscollection',
            unique_together={('account', 'collection_type', 'installment_no', 'is_expected')},
        ),
    ]
