# Generated by Django 5.2.3 on 2026-02-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
        ('branch', '0002_initial'),
        ('savings', '0013_savingscollection_installment_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAgentAssign',
            fields=[
                ('assignment_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignments', to='savings.savingsaccountapplication')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_agent_assignments', to='agent.agent')),
                ('assigned_by_branch_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_agent_assignments', to='branch.branchemployee')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
