# Generated by Django 5.2.3 on 2026-02-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_savingsagentassign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsagentassign',
            old_name='assigned_by_branch_employee',
            new_name='assigned_by',
        ),
        migrations.AlterField(
            model_name='savingsagentassign',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_savings_accounts', to='branch.branchemployee'),
        ),
        migrations.AddField(
            model_name='savingsagentassign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='savingsagentassign',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('account',), name='unique_active_savings_agent_assign_per_account'),
        ),
    ]
