# Generated by Django 5.2.3 on 2026-02-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0019_savingsaccountapplication_nominee_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimedeposit',
            options={'ordering': ['deposit_amount', 'tenure', 'tenure_unit', 'payable_amount'], 'verbose_name': 'One Time Deposit', 'verbose_name_plural': 'One Time Deposits'},
        ),
        migrations.AlterUniqueTogether(
            name='onetimedeposit',
            unique_together={('deposit_amount', 'tenure', 'tenure_unit')},
        ),
        migrations.AddField(
            model_name='onetimedeposit',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='onetimedeposit',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
