# Generated by Django 5.2.3 on 2026-05-16 06:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0020_alter_onetimedeposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccountapplication',
            name='nominee_kyc_document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/nominee/kyc/'),
        ),
    ]
