# Generated by Django 5.2.3 on 2026-01-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocument',
            name='savings_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='savings.savingsaccountapplication'),
        ),
    ]
