# Generated by Django 5.2.3 on 2026-01-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_documentrequest_savings_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof (Aadhar/PAN)'), ('id_proof_back', 'ID Proof Back'), ('income_proof', 'Income Proof'), ('photo', 'Passport Photo'), ('signature', 'Digital Signature'), ('collateral', 'Collateral Documents'), ('residential_proof', 'Residential Proof'), ('residential_proof_file', 'Residential Proof')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentreupload',
            name='document_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof (Aadhar/PAN)'), ('id_proof_back', 'ID Proof Back'), ('income_proof', 'Income Proof'), ('photo', 'Passport Photo'), ('signature', 'Digital Signature'), ('collateral', 'Collateral Documents'), ('residential_proof', 'Residential Proof'), ('residential_proof_file', 'Residential Proof')], max_length=30),
        ),
    ]
