# Generated by Django 5.2.3 on 2026-02-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_documentrequest_document_type_and_documentreupload_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocument',
            name='pan_card_document',
            field=models.FileField(blank=True, null=True, upload_to='static/customer/pan_card/'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof (Aadhar/PAN)'), ('pan_card_document', 'PAN Card Document'), ('id_proof_back', 'ID Proof Back'), ('income_proof', 'Income Proof'), ('photo', 'Passport Photo'), ('signature', 'Digital Signature'), ('collateral', 'Collateral Documents'), ('residential_proof', 'Residential Proof'), ('residential_proof_file', 'Residential Proof')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentreupload',
            name='document_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof (Aadhar/PAN)'), ('pan_card_document', 'PAN Card Document'), ('id_proof_back', 'ID Proof Back'), ('income_proof', 'Income Proof'), ('photo', 'Passport Photo'), ('signature', 'Digital Signature'), ('collateral', 'Collateral Documents'), ('residential_proof', 'Residential Proof'), ('residential_proof_file', 'Residential Proof')], max_length=30),
        ),
    ]
