# Generated by Cascade on 2026-03-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0002_alter_headquarteremployee_image_and_more'),
        ('loan', '0005_customerdocument_pan_card_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMainCategory',
            fields=[
                ('main_category_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loan_main_categories', to='headquater.headquarteremployee')),
            ],
            options={
                'verbose_name': 'Loan Main Category',
                'verbose_name_plural': 'Loan Main Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='loancategory',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_categories', to='loan.loanmaincategory'),
        ),
        migrations.AlterField(
            model_name='loancategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='loancategory',
            unique_together={('main_category', 'name')},
        ),
    ]
