# Generated by Django 5.2.3 on 2026-03-12 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_main_category_for_masters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMainCategory',
            fields=[
                ('main_category_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobile_main_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Main Category',
                'verbose_name_plural': 'Mobile Main Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MobileSubCategory',
            fields=[
                ('sub_category_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobile_sub_categories', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='loan.mobilemaincategory')),
            ],
            options={
                'verbose_name': 'Mobile Sub Category',
                'verbose_name_plural': 'Mobile Sub Categories',
                'ordering': ['name'],
                'unique_together': {('main_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobiles', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='loan.mobilesubcategory')),
            ],
            options={
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
                'ordering': ['name'],
                'unique_together': {('sub_category', 'name')},
            },
        ),
    ]
