# Generated by Django 5.2.3 on 2026-03-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_remove_mobilemaincategory_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='loan_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='loan.loancategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='loan_main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='loan.loanmaincategory'),
        ),
    ]
