# Generated by Django 5.2.3 on 2026-03-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_productcategory_loan_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloandetail',
            name='loan_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerloandetail',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loans', to='loan.product'),
        ),
    ]
