# Generated by Django 5.2.3 on 2026-03-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_customerloandetail_loan_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerloandetail',
            old_name='product_id',
            new_name='product',
        ),
    ]
