# Generated by Django 5.2.3 on 2026-03-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
        ('headquater', '0004_alter_headquarteremployee_image_and_more'),
        ('loan', '0014_rename_product_id_customerloandetail_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='agent.agent')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='headquater.branch')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='loan.shop'),
        ),
        migrations.CreateModel(
            name='ShopBankAccount',
            fields=[
                ('bank_account_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='loan.shop')),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='shop_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='loan.shopbankaccount'),
        ),
        migrations.AddIndex(
            model_name='shopbankaccount',
            index=models.Index(fields=['shop'], name='loan_shopba_shop_id_6dfbee_idx'),
        ),
        migrations.AddIndex(
            model_name='shopbankaccount',
            index=models.Index(fields=['account_number'], name='loan_shopba_account_3788d5_idx'),
        ),
    ]
