# Generated by Django 5.2.3 on 2026-03-27 04:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_shop_loanapplication_shop_shopbankaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
