# Generated by Django 5.2.3 on 2026-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_shopbankaccount_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmaincategory',
            name='is_shop_active',
            field=models.BooleanField(default=False),
        ),
    ]
