# Generated by Django 5.2.3 on 2026-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_loanmaincategory_is_shop_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='customer_snapshot',
            field=models.JSONField(blank=True, help_text='JSON snapshot of CustomerDetail (personal info) at application time. Used so old loans show historical data while current customer record stays updated.', null=True),
        ),
    ]
