# Generated by Django 5.2.3 on 2026-03-30
from decimal import Decimal
from django.db import migrations
from datetime import date, datetime
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db.models.fields.files import FieldFile


def populate_snapshots(apps, schema_editor):
    LoanApplication = apps.get_model('loan', 'LoanApplication')
    CustomerDetail = apps.get_model('loan', 'CustomerDetail')
    CustomerAddress = apps.get_model('loan', 'CustomerAddress')
    # CustomerAccount - adjust app_label + model name if different
    CustomerAccount = apps.get_model('loan', 'CustomerAccount')  
    CustomerDocument = apps.get_model('loan', 'CustomerDocument')

    for loan in LoanApplication.objects.filter(customer_snapshot__isnull=True).iterator():
        if not loan.customer:
            continue  # Skip loans without customer

        snapshot = {
            "snapshot_timestamp": datetime.now().isoformat(),
            "customer_details": {},
            "address": {},
            "bank_details": {},
            "documents": []
        }

        customer = loan.customer

        # === 1. CustomerDetail snapshot ===
        customer_fields = [
            f.name for f in CustomerDetail._meta.fields
            if f.name not in ['id', 'customer_id', 'created_at', 'updated_at', 'last_update',
                              'loan_application', 'agent', 'branch', 'branch_rejection_reason']
        ]

        for field_name in customer_fields:
            value = getattr(customer, field_name, None)
            if isinstance(value, (date, datetime)):
                value = value.isoformat()
            elif isinstance(value, FieldFile):
                # FileField / ImageField → store path only
                value = default_storage.url(value.name)
            elif isinstance(value, Decimal):   # if you have any Decimal fields
                value = str(value)
            snapshot["customer_details"][field_name] = value

        # === 2. Address (OneToOne) ===
        try:
            address = CustomerAddress.objects.filter(customer=customer).first()
            if address:
                addr_fields = [
                    f.name for f in CustomerAddress._meta.fields
                    if f.name not in ['id', 'customer_id', 'customer', 'loan_application',
                                      'agent', 'branch', 'submitted_at', 'last_update']
                ]
                for field_name in addr_fields:
                    value = getattr(address, field_name, None)
                    if isinstance(value, (date, datetime)):
                        value = value.isoformat()
                    elif isinstance(value, FieldFile):
                        # FileField / ImageField → store path only
                        value = default_storage.url(value.name)
                    snapshot["address"][field_name] = value
        except:
            pass  # Address may not exist

        # === 3. Bank Details ===
        try:
            bank = CustomerAccount.objects.filter(customer=customer).first()
            if bank:
                bank_fields = [
                    f.name for f in CustomerAccount._meta.fields
                    if f.name not in ['id', 'customer_id', 'customer', 'loan_application',
                                      'agent', 'branch', 'submitted_at', 'last_update']
                ]
                for field_name in bank_fields:
                    value = getattr(bank, field_name, None)
                    if isinstance(value, (date, datetime)):
                        value = value.isoformat()
                    elif isinstance(value, FieldFile):
                        # FileField / ImageField → store path only
                        value = default_storage.url(value.name)
                    snapshot["bank_details"][field_name] = value
        except:
            pass

        # === 4. Documents (adjust relation if needed) ===
        try:
            # If CustomerDocument has OneToOne with loan_application (as in your model)
            if hasattr(loan, 'documents') and loan.documents:
                doc = loan.documents
                doc_fields = [
                    f.name for f in CustomerDocument._meta.fields
                    if f.name not in ['id', 'loan_application', 'savings_application',
                                      'agent', 'branch', 'submitted_at', 'last_update']
                ]
                doc_snapshot = {}
                for field_name in doc_fields:
                    value = getattr(doc, field_name, None)
                    # FileField / ImageField → store path only
                    if isinstance(value, FieldFile):
                        value = default_storage.url(value.name)
                    elif isinstance(value, (date, datetime)):
                        value = value.isoformat()
                    doc_snapshot[field_name] = value

                snapshot["documents"] = [doc_snapshot]

            # Alternative: if you have multiple documents via reverse relation
            # docs = customer.customerdocuments.all()  # uncomment if using this pattern

        except:
            snapshot["documents"] = []

        # Assign and save
        loan.customer_snapshot = snapshot
        loan.save(update_fields=['customer_snapshot'])


def reverse_code(apps, schema_editor):
    # Optional: clear snapshots on rollback (be careful in production)
    LoanApplication = apps.get_model('loan', 'LoanApplication')
    LoanApplication.objects.all().update(customer_snapshot=None)


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_loanapplication_customer_snapshot'),  # Update with your actual previous migration
    ]

    operations = [
        migrations.RunPython(populate_snapshots, reverse_code=reverse_code),
    ]