# Generated by Django 5.2.3 on 2026-04-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_auto_20260330_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='guarantor_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='static/customer/guarantor_id_proof/'),
        ),
        migrations.AddField(
            model_name='customerloandetail',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerloandetail',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerloandetail',
            name='processing_fee_snapshot',
            field=models.JSONField(blank=True, help_text='JSON snapshot of processing fee details at application time.', null=True),
        ),
        migrations.AddField(
            model_name='customerloandetail',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
