# Generated by Django 5.2.3 on 2026-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_customerdetail_guarantor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopbankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopbankaccount',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
