# Generated by Django 5.2.3 on 2026-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_alter_shopbankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/customer/photo/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='static/customer/signature/'),
        ),
    ]
