# Generated by Django 5.2.3 on 2026-04-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_alter_customerdetail_pan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('success', 'Success'), ('reject', 'Rejected'), ('rejected_by_branch', 'Rejected by Branch'), ('inactive', 'Inactive'), ('document_requested', 'Document Requested by Branch'), ('resubmitted', 'Resubmitted - Pending Branch Review'), ('branch_document_accepted', 'Branch Accepted Document'), ('branch_approved', 'Branch Approved - Pending HQ Approval'), ('branch_resubmitted', 'Reuploaded - Pending HQ review'), ('hq_document_accepted', 'HQ Accepted Document'), ('hq_resubmitted', 'HQ Requested Resubmission'), ('hq_approved', 'HQ Approved'), ('hq_rejected', 'HQ Rejected'), ('disbursed', 'Disbursed'), ('disbursed_fund_released', 'Disbursed - Fund Released'), ('document_requested_by_hq', 'Document Requested by HQ'), ('closed', 'Closed')], default='pending', max_length=32),
        ),
    ]
