# Generated by Django 5.2.3 on 2026-05-05 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_add_is_demo'),
        ('headquater', '0011_alter_headquarteremployee_image_and_more'),
        ('loan', '0023_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='agent.agent'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='headquater.branch'),
        ),
    ]
