# Generated by Django 5.2.3 on 2026-05-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_alter_shop_agent_alter_shop_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_by',
            field=models.CharField(choices=[('agent', 'Agent'), ('branch', 'Branch')], default='agent', max_length=10),
        ),
    ]
