# Generated by Django 5.2.3 on 2026-05-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0025_add_created_by_to_shop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loaninterest',
            unique_together=set(),
        ),
    ]
