# Generated by Django 5.2.3 on 2026-05-06 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_remove_unique_interest_rate_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loaninterest',
            unique_together={('main_category', 'rate_of_interest', 'created_by')},
        ),
    ]
