# Generated by Django 5.2.3 on 2026-05-11 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_alter_loaninterest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loanmaincategory',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('created_by', 'name'), name='unique_created_by_name_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='loanmaincategory',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name',), name='unique_name_when_created_by_null'),
        ),
    ]
