# Generated by Django 5.2.3 on 2026-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0028_loanmaincategory_unique_created_by_name_when_not_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmaincategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
