# Generated by Django 5.2.3 on 2026-05-13 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0029_alter_loanmaincategory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deductions',
            unique_together={('main_category', 'deduction_name', 'deduction_type', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='loancategory',
            unique_together={('main_category', 'name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='loantenure',
            unique_together={('interest_rate', 'value', 'unit', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sub_category', 'name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together={('main_category', 'name', 'created_by')},
        ),
    ]
