# Generated by Django 5.2.3 on 2026-05-16 06:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_alter_deductions_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='collateral',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/collateral/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='guarantor_id_proof',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/guarantor_id_proof/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='id_proof',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/id_proof/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='id_proof_back',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/id_proof/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='income_proof',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/income_proof/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='pan_card_document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/pan_card/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/photo/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='residential_proof_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/residential_proof/'),
        ),
        migrations.AlterField(
            model_name='customerdocument',
            name='signature',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/signature/'),
        ),
    ]
