# Generated by Django 5.2.3 on 2026-05-18 10:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0031_alter_customerdocument_collateral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentreupload',
            name='uploaded_file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='static/customer/reuploads/'),
        ),
    ]
