# Generated by Django 5.2.3 on 2026-06-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0032_alter_documentreupload_uploaded_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loantenure',
            unique_together={('interest_rate', 'value', 'unit')},
        ),
    ]
