# Generated by Django 5.2.3 on 2026-06-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0033_alter_loantenure_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deductions',
            unique_together={('main_category', 'deduction_name', 'deduction_type')},
        ),
        migrations.AlterUniqueTogether(
            name='loancategory',
            unique_together={('main_category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='loaninterest',
            unique_together={('main_category', 'rate_of_interest')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sub_category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together={('main_category', 'name')},
        ),
    ]
