# Generated by Django 5.2.3 on 2026-08-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0034_alter_deductions_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loaninterest',
            unique_together=set(),
        ),
    ]
