# Generated by Django 5.2.3 on 2026-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0035_alter_loaninterest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deductions',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='loancategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='loantenure',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together=set(),
        ),
    ]
