# Generated by Django 5.2.3 on 2026-09-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0036_alter_deductions_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBureauCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', models.CharField(default='EQUFAX (Surepass)', max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Equifax score (300-900). Null if no history / failed.', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('no_history', 'No Credit History'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('decision', models.CharField(choices=[('pass', 'Pass'), ('manual_review', 'Manual Review'), ('fail', 'Fail')], default='manual_review', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, help_text='Full bureau/API response for audit.', null=True)),
                ('fetched_by', models.CharField(blank=True, help_text='Who/what triggered the pull.', max_length=100, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_checks', to='loan.customerdetail')),
                ('loan_application', models.ForeignKey(blank=True, help_text='Null for pre-application checks; linked when the application is submitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_checks', to='loan.loanapplication')),
            ],
            options={
                'verbose_name': 'Credit Bureau Check',
                'verbose_name_plural': 'Credit Bureau Checks',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['loan_application', '-fetched_at'], name='loan_credit_loan_ap_7d88bb_idx')],
            },
        ),
    ]
