# Generated by Django 5.2.3 on 2026-01-18 17:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import headquater.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadquartersWallet',
            fields=[
                ('wallet_id', models.CharField(default=headquater.models.HeadquartersWallet.generate_wallet_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=10)),
                ('name', models.CharField(max_length=255, null=True)),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('account_number', models.CharField(max_length=255, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Headquarters Wallet',
                'verbose_name_plural': 'Headquarters Wallets',
            },
        ),
        migrations.CreateModel(
            name='HeadquarterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, help_text='Profile Image of Headquater Employee', null=True, storage=django.core.files.storage.FileSystemStorage(location='F:\\sundaram\\media'), upload_to='hq/employee/profile/')),
                ('address', models.TextField(blank=True, null=True)),
                ('is_headquater_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='headquarter_employees', related_query_name='headquarter_employee', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='headquarter_employees', related_query_name='headquarter_employee', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Headquarter Employee',
                'verbose_name_plural': 'Headquarter Employees',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255, unique=True)),
                ('address_line_1', models.CharField(default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('postal_code', models.CharField(default='', max_length=6)),
                ('country', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('manager_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('wallet_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='HeadquartersTransactions',
            fields=[
                ('transaction_id', models.CharField(default=headquater.models.HeadquartersTransactions.generate_transaction_id, editable=False, max_length=12, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, help_text='Purpose of the transaction (from Chart of Accounts)', max_length=255, null=True)),
                ('code', models.CharField(blank=True, help_text='Account code from Chart of Accounts', max_length=50, null=True)),
                ('proof_document', models.FileField(blank=True, help_text='Upload proof document for this transaction (e.g., bank receipt, UPI screenshot)', null=True, storage=django.core.files.storage.FileSystemStorage(location='F:\\sundaram\\static'), upload_to='hq/transaction_proof/')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for the transaction (e.g., UTR, Cheque number)', max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='headquater.headquarterswallet')),
            ],
            options={
                'verbose_name': 'Headquarters Transaction',
                'verbose_name_plural': 'Headquarters Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='FundTransfers',
            fields=[
                ('transfer_id', models.CharField(default=headquater.models.FundTransfers.generate_transfer_id, editable=False, max_length=13, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, help_text='Stores the transaction_id (HQ or Branch) that initiated the transfer.', max_length=100, null=True)),
                ('transfer_to', models.CharField(blank=True, help_text='Destination identifier: store Branch.branch_id when HQ→Branch, or the Headquarters ID when Branch→HQ.', max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_method', models.CharField(blank=True, max_length=20, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_account', models.ForeignKey(blank=True, help_text='Destination BranchAccount when applicable (e.g., HQ→Branch cash/bank transfers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers', to='branch.branchaccount')),
                ('branch_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers', to='branch.branchtransaction')),
                ('hq_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers', to='headquater.headquarterstransactions')),
            ],
            options={
                'verbose_name': 'Fund Transfer',
                'verbose_name_plural': 'Fund Transfers',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role_type', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('finance_manager', 'Finance Manager'), ('operations_manager', 'Operations Manager'), ('compliance_officer', 'Compliance Officer'), ('data_analyst', 'Data Analyst'), ('customer_support_lead', 'Customer Support Lead')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='role_permissions', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='headquarteremployee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headquarter_employees', to='headquater.role'),
        ),
    ]
