# Generated by Django 5.2.3 on 2026-04-03 07:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0005_alter_headquarteremployee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarteremployee',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Image of Headquater Employee', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\user\\Dropbox\\PC\\Desktop\\Sundaram folder\\sundaram\\media'), upload_to='hq/employee/profile/'),
        ),
        migrations.AlterField(
            model_name='headquarterstransactions',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Upload proof document for this transaction (e.g., bank receipt, UPI screenshot)', null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\user\\Dropbox\\PC\\Desktop\\Sundaram folder\\sundaram\\static'), upload_to='hq/transaction_proof/'),
        ),
    ]
