# Generated by Django 5.2.3 on 2026-04-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0004_headquarteremployee_trial_expiry_date'),
        ('headquater', '0008_alter_headquarteremployee_image_and_more'),
    ]

    operations = [
    ]
