# Generated by Django 5.2.3 on 2026-05-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0009_alter_headquarteremployee_image_and_more'),
        ('headquater', '0009_merge_20260428_1743'),
    ]

    operations = [
    ]
