# Generated by Django 5.2.3 on 2026-05-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0011_alter_headquarteremployee_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarterswallet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_wallets_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
