# Generated by Django 5.2.3 on 2026-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0012_add_created_by_to_hq_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='headquarteremployee',
            name='demo_credit_count',
            field=models.IntegerField(default=0, help_text='Number of demo credit for live otp application'),
        ),
    ]
