# Generated by Django 5.2.3 on 2026-05-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0013_headquarteremployee_demo_credit_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headquarteremployee',
            old_name='demo_credit_count',
            new_name='demo_credit',
        ),
    ]
