# Generated by Django 5.2.3 on 2026-05-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0013_alter_headquarteremployee_image_and_more'),
        ('headquater', '0014_rename_demo_credit_count_headquarteremployee_demo_credit'),
    ]

    operations = [
    ]
