# Generated by Django 5.2.3 on 2026-05-16 06:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0014_rename_demo_credit_count_headquarteremployee_demo_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarteremployee',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile Image of Headquater Employee', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hq/employee/profile/'),
        ),
        migrations.AlterField(
            model_name='headquarterstransactions',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Upload proof document for this transaction (e.g., bank receipt, UPI screenshot)', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hq/transaction_proof/'),
        ),
    ]
