# Generated by Django 5.2.3 on 2026-05-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headquater', '0015_alter_headquarteremployee_image_and_more'),
        ('headquater', '0015_merge_20260513_1232'),
    ]

    operations = [
    ]
