# Generated by Django 5.2.3 on 2026-01-18 17:48

import agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('agent', 'Agent')], default='agent', max_length=20)),
                ('area', models.CharField(max_length=255)),
                ('id_proof', models.FileField(upload_to=agent.models.agent_id_proof_upload_path)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=agent.models.agent_photo_upload_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
