# Generated by Cascade on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE agent_agent "
                        "ADD COLUMN IF NOT EXISTS is_demo boolean;"
                        "UPDATE agent_agent SET is_demo = false WHERE is_demo IS NULL;"
                        "ALTER TABLE agent_agent ALTER COLUMN is_demo SET DEFAULT false;"
                        "ALTER TABLE agent_agent ALTER COLUMN is_demo SET NOT NULL;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE agent_agent "
                        "DROP COLUMN IF EXISTS is_demo;"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='agent',
                    name='is_demo',
                    field=models.BooleanField(default=False),
                )
            ],
        )
    ]
