# Generated by Django 5.2.3 on 2026-05-16 06:36

import agent.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_add_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id_proof',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=agent.models.agent_id_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=agent.models.agent_photo_upload_path),
        ),
    ]
