# Generated by Django 5.2.3 on 2026-01-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDepositDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coin', models.PositiveIntegerField(default=0)),
                ('cash', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BranchAccount',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'branch_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='Is Manager')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branch/profile/')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('gov_id_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('other', 'Other')], default='aadhar', max_length=50)),
                ('gov_id_number', models.CharField(max_length=100, unique=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Branch Employee',
                'verbose_name_plural': 'Branch Employees',
                'db_table': 'branch_employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(choices=[('branch', 'Branch Operations'), ('role', 'Role Management'), ('staff', 'Staff Management'), ('agent', 'Agent Management'), ('loan', 'Loan Management'), ('emi', 'EMI Management'), ('customer', 'Customer Management'), ('payment', 'Payment Processing'), ('report', 'Reports')], default='branch', max_length=50)),
            ],
            options={
                'verbose_name': 'Branch Permission',
                'verbose_name_plural': 'Branch Permissions',
                'db_table': 'branch_permissions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Role',
                'verbose_name_plural': 'Branch Roles',
                'db_table': 'branch_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchTransaction',
            fields=[
                ('transaction_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('purpose', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_to_from', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'branch_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='AgentDeposit',
            fields=[
                ('deposit_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coin_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('online_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mismatch', models.BooleanField(default=False)),
                ('daily_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saving_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('others_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='agent.agent')),
            ],
        ),
    ]
