# Generated by Django 5.2.3 on 2026-01-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('headquater', '0001_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdeposit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_deposits', to='headquater.branch'),
        ),
        migrations.AddField(
            model_name='agentdepositdenomination',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='branch.agentdeposit'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='headquater.branch'),
        ),
        migrations.AddField(
            model_name='branchemployee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='headquater.branch'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_created', to='branch.branchemployee'),
        ),
        migrations.AddField(
            model_name='branchaccount',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_updated', to='branch.branchemployee'),
        ),
        migrations.AddField(
            model_name='agentdeposit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deposits_created', to='branch.branchemployee'),
        ),
        migrations.AddField(
            model_name='agentdeposit',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits_received', to='branch.branchemployee'),
        ),
        migrations.AddField(
            model_name='branchrole',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_roles', to='headquater.branch'),
        ),
        migrations.AddField(
            model_name='branchrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='branch_roles', to='branch.branchpermission', verbose_name='branch permissions'),
        ),
        migrations.AddField(
            model_name='branchemployee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branch.branchrole'),
        ),
        migrations.AddField(
            model_name='branchtransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='headquater.branch'),
        ),
        migrations.AddField(
            model_name='branchtransaction',
            name='branch_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='branch.branchaccount'),
        ),
        migrations.AddField(
            model_name='branchtransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_created', to='branch.branchemployee'),
        ),
        migrations.AddField(
            model_name='branchtransaction',
            name='disbursement_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transactions', to='loan.disbursementlog'),
        ),
        migrations.AddIndex(
            model_name='agentdepositdenomination',
            index=models.Index(fields=['deposit'], name='branch_agen_deposit_80ce80_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchrole',
            unique_together={('name', 'branch')},
        ),
        migrations.AddIndex(
            model_name='branchemployee',
            index=models.Index(fields=['is_manager'], name='branch_empl_is_mana_f1c2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='branchemployee',
            index=models.Index(fields=['email'], name='branch_empl_email_fc07ca_idx'),
        ),
        migrations.AddIndex(
            model_name='branchemployee',
            index=models.Index(fields=['phone_number'], name='branch_empl_phone_n_e74b45_idx'),
        ),
    ]
