# Generated by Django 5.2.3 on 2026-04-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
        ('branch', '0002_initial'),
        ('loan', '0020_customerdetail_guarantor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtransaction',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transactions', to='agent.agent'),
        ),
        migrations.AddField(
            model_name='branchtransaction',
            name='loan_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_transactions', to='loan.loanapplication'),
        ),
        migrations.AddField(
            model_name='branchtransaction',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_transactions', to='loan.shop'),
        ),
        migrations.AlterField(
            model_name='branchtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_created', to='branch.branchemployee'),
        ),
    ]
