# Generated by Django 5.2.3 on 2026-05-16 06:36

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branchtransaction_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchemployee',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='branch/profile/'),
        ),
    ]
